export type EntryListPlayer = {
  name: string;
  country: string;
  rank: number | null;
  note?: string;
};

export type Aug17EntryList = {
  slug: string;
  name: string;
  level: string;
  surface: 'Hard' | 'Clay';
  atpCode: string;
  main: EntryListPlayer[];
  mainNext: EntryListPlayer[];
  qualifying: EntryListPlayer[];
  qualifyingNext: EntryListPlayer[];
  recentMovement: string[];
};

export const AUG17_MAIN_SOURCE = {
  label: 'LiveTennis — Aug 11 update',
  url: 'https://www.livetennis.it/post/469551/challenger-cancun-quebec-city-kingston-roehampton-praga-e-sion-la-situazione-aggiornata-darderi-si-cancella-da-cancun/',
  checkedAt: 'Aug 11, 2026 · 12:54',
};

export const AUG17_QUAL_SOURCE = {
  label: 'TickTock Tennis — Aug 10 snapshot',
  url: 'https://entries.ticktocktennis.com/atp',
  checkedAt: 'Aug 10, 2026 · 11:00 AM ET',
};

const p = (name: string, country: string, rank: number | null, note?: string): EntryListPlayer => ({
  name,
  country,
  rank,
  ...(note ? { note } : {}),
});

export const AUG17_ENTRY_LISTS: Aug17EntryList[] = [
  {
    slug: 'cancun',
    name: 'Cancun',
    level: 'CH 175',
    surface: 'Hard',
    atpCode: '3009',
    main: [
      p('Juan Manuel Cerundolo', 'ARG', 50),
      p('Sebastian Baez', 'ARG', 53),
      p('Roman Andres Burruchaga', 'ARG', 58),
      p('Thiago Agustin Tirante', 'ARG', 64),
      p('Adolfo Daniel Vallejo', 'PAR', 65),
      p('Denis Shapovalov', 'CAN', 68),
      p('Vit Kopriva', 'CZE', 70),
      p('Kamil Majchrzak', 'POL', 72),
      p('Camilo Ugo Carabelli', 'ARG', 75),
      p('Roman Safiullin', 'RUS', 92),
      p('Adam Walton', 'AUS', 96),
      p('Francisco Comesana', 'ARG', 100),
      p('Damir Dzumhur', 'BIH', 102),
      p('Coleman Wong', 'HKG', 108),
      p('Otto Virtanen', 'FIN', 115),
      p('Dalibor Svrcina', 'CZE', 116),
      p('Yibing Wu', 'CHN', 117),
      p('Michael Zheng', 'USA', 118),
      p('Moise Kouame', 'FRA', 213, 'NG'),
      p('Darwin Blanch', 'USA', 226, 'NG'),
      p('Henrique Rocha', 'POR', 123, 'IN'),
    ],
    mainNext: [
      p('Sebastian Ofner', 'AUT', 124),
      p('Stan Wawrinka', 'SUI', 125),
      p('Arthur Gea', 'FRA', 127),
      p('Pablo Llamas Ruiz', 'ESP', 129),
      p('Nicolas Mejia', 'COL', 131),
      p('Alexandre Muller', 'FRA', 132),
      p('Tomas Barrios Vera', 'CHI', 138),
      p('Cristian Garin', 'CHI', 139),
      p('Mackenzie McDonald', 'USA', 145),
    ],
    qualifying: [
      p('Nicolas Mejia', 'COL', 131),
      p('Tomas Barrios Vera', 'CHI', 138),
      p('Seongchan Hong', 'KOR', 147),
      p('Timofey Skatov', 'KAZ', 150),
      p('Moez Echargui', 'TUN', 151),
      p('Felipe Meligeni Alves', 'BRA', 162),
      p('Borna Gojo', 'CRO', 164),
      p('Gauthier Onclin', 'BEL', 170),
      p('Lloyd Harris', 'RSA', 182),
      p('David Jorda Sanchis', 'ESP', 188),
      p('Thiago Seyboth Wild', 'BRA', 206),
      p('Luka Pavlovic', 'FRA', 208),
      p('Laslo Djere', 'SRB', 210),
    ],
    qualifyingNext: [
      p('Sebastian Ofner', 'AUT', 124),
      p('Stan Wawrinka', 'SUI', 125),
      p('Arthur Gea', 'FRA', 127),
      p('Pablo Llamas Ruiz', 'ESP', 129),
      p('Alexandre Muller', 'FRA', 132),
      p('Cristian Garin', 'CHI', 139),
      p('Mackenzie McDonald', 'USA', 145),
    ],
    recentMovement: ['Luciano Darderi withdrew', 'Henrique Rocha moved into the main draw'],
  },
  {
    slug: 'quebec-city',
    name: 'Quebec City',
    level: 'CH 175',
    surface: 'Hard',
    atpCode: '3103',
    main: [
      p('Alexander Blockx', 'BEL', 32),
      p('Zizou Bergs', 'BEL', 36),
      p('Arthur Fery', 'GBR', 37),
      p('Luca Van Assche', 'FRA', 48),
      p('Quentin Halys', 'FRA', 52),
      p('Terence Atmane', 'FRA', 56),
      p('Juncheng Shang', 'CHN', 56, 'PR'),
      p('Botic van de Zandschulp', 'NED', 69),
      p('James Duckworth', 'AUS', 83),
      p('Giovanni Mpetshi Perricard', 'FRA', 87),
      p('Jan Choinski', 'GBR', 88),
      p('Hugo Gaston', 'FRA', 90),
      p('Rinky Hijikata', 'AUS', 93),
      p('Sho Shimabukuro', 'JPN', 94),
      p('Dino Prizmic', 'CRO', 98),
      p('Gabriel Diallo', 'CAN', 99),
      p('Benjamin Bonzi', 'FRA', 101),
      p('Alexei Popyrin', 'AUS', 103),
      p('Aleksandar Vukic', 'AUS', 105),
      p('Nicolai Budkov Kjaer', 'NOR', 144, 'NG'),
      p('Rei Sakamoto', 'JPN', 166, 'NG'),
    ],
    mainNext: [
      p('Jesper de Jong', 'NED', 106),
      p('Eliot Spizzirri', 'USA', 109),
      p('Jacob Fearnley', 'GBR', 110),
      p('Yunchaokete Bu', 'CHN', 111),
      p('Toby Samuel', 'GBR', 112),
      p('Patrick Kypson', 'USA', 113),
      p('Shintaro Mochizuki', 'JPN', 114),
      p('Titouan Droguet', 'FRA', 119),
      p('Kyrian Jacquet', 'FRA', 120),
      p('Dane Sweeny', 'AUS', 121),
    ],
    qualifying: [
      p('Eliot Spizzirri', 'USA', 109),
      p('Yunchaokete Bu', 'CHN', 111),
      p('Patrick Kypson', 'USA', 113),
      p('Kyrian Jacquet', 'FRA', 120),
      p("Christopher O'Connell", 'AUS', 126),
      p('Jurij Rodionov', 'AUT', 136),
      p('Andrea Pellegrino', 'ITA', 137),
      p('Mackenzie McDonald', 'USA', 145),
      p('Francesco Maestrelli', 'ITA', 149),
      p('Dusan Lajovic', 'SRB', 152),
      p('Chris Rodesch', 'LUX', 153),
      p('Stefanos Sakellaridis', 'GRE', 155),
      p('Soonwoo Kwon', 'KOR', 158),
    ],
    qualifyingNext: [
      p('Jesper de Jong', 'NED', 106),
      p('Jacob Fearnley', 'GBR', 110),
      p('Toby Samuel', 'GBR', 112),
      p('Shintaro Mochizuki', 'JPN', 114),
      p('Titouan Droguet', 'FRA', 119),
      p('Dane Sweeny', 'AUS', 121),
    ],
    recentMovement: [],
  },
  {
    slug: 'kingston',
    name: 'Kingston',
    level: 'CH 75',
    surface: 'Hard',
    atpCode: '3121',
    main: [
      p('Valentin Royer', 'FRA', 78),
      p('Gustavo Heide', 'BRA', 134),
      p('Pedro Martinez', 'ESP', 148),
      p('Juan Carlos Prado Angelo', 'BOL', 157),
      p('Gonzalo Bueno', 'PER', 160),
      p('Daniil Glinka', 'EST', 169),
      p('Bernard Tomic', 'AUS', 171),
      p('Joel Schwaerzler', 'AUT', 183),
      p('Federico Agustin Gomez', 'ARG', 191),
      p('Lautaro Midon', 'ARG', 196),
      p('Elias Ymer', 'SWE', 203),
      p('Clement Chidekh', 'FRA', 204),
      p('Harry Wendelken', 'GBR', 205),
      p('Liam Draxl', 'CAN', 211),
      p('Felix Gill', 'GBR', 219),
      p('Guido Ivan Justo', 'ARG', 223),
      p('Dan Added', 'FRA', 224),
      p('Franco Roncadelli', 'URU', 225),
      p('Guto Miguel', 'BRA', null, 'JR 11'),
      p('Benjamin Willwerth', 'USA', null, 'JR 19'),
      p('Oliver Crawford', 'GBR', 228, 'IN'),
    ],
    mainNext: [
      p('Frederico Ferreira Silva', 'POR', 235),
      p('Jay Clarke', 'GBR', 237),
      p('Florent Bax', 'FRA', 247),
      p('Harold Mayot', 'FRA', 255),
      p('Andy Andrade', 'ECU', 262),
      p('Juan Pablo Ficovich', 'ARG', 273),
      p('Alvaro Guillen Meza', 'ECU', 277),
      p('Charles Broom', 'GBR', 283),
      p('Yanki Erel', 'TUR', 287),
    ],
    qualifying: [
      p('Hugo Dellien', 'BOL', 143),
      p('Frederico Ferreira Silva', 'POR', 235),
      p('Jay Clarke', 'GBR', 237),
      p('Florent Bax', 'FRA', 247),
      p('Andy Andrade', 'ECU', 262),
      p('Juan Pablo Ficovich', 'ARG', 273),
      p('Alvaro Guillen Meza', 'ECU', 277),
      p('Murphy Cassone', 'USA', 285),
      p('Igor Marcondes', 'BRA', 296),
      p('Daniel Milavsky', 'USA', 325),
      p('Paul Jubb', 'GBR', 335),
      p('Blaise Bicknell', 'JAM', 344),
      p('Mitchell Krueger', 'USA', 346),
      p('Ivan Marrero Curbelo', 'ESP', 356),
      p('Garrett Johns', 'USA', 370),
      p('Andres Martin', 'USA', 381),
      p('Edward Winter', 'AUS', 391),
      p('Lucas Andrade Da Silva', 'BRA', null),
      p('Aidan Kim', 'USA', null),
    ],
    qualifyingNext: [
      p('Harold Mayot', 'FRA', 255),
      p('Charles Broom', 'GBR', 283),
      p('Yanki Erel', 'TUR', 287),
    ],
    recentMovement: ['Liam Broady withdrew', 'Oliver Crawford moved into the main draw'],
  },
  {
    slug: 'prague',
    name: 'Prague',
    level: 'CH 75',
    surface: 'Clay',
    atpCode: '600',
    main: [
      p('Zdenek Kolar', 'CZE', 154),
      p('Vitaliy Sachko', 'UKR', 192),
      p('Kimmer Coppejans', 'BEL', 218),
      p('Gilles Arnaud Bailly', 'BEL', 230),
      p('Kilian Feldbausch', 'SUI', 242),
      p('Andrej Nedic', 'BIH', 244),
      p('Sumit Nagal', 'IND', 246),
      p('Matias Soto', 'CHI', 252),
      p('Matej Dodig', 'CRO', 258),
      p('Chun Hsin Tseng', 'TWN', 260),
      p('Martin Krumich', 'CZE', 261),
      p('Cezar Cretu', 'ROU', 263),
      p('Alex Barrena', 'ARG', 264),
      p('Hynek Barton', 'CZE', 268),
      p('Nick Hardt', 'DOM', 275),
      p('Juan Bautista Torres', 'ARG', 276),
      p('Filip Jianu', 'ROU', 279),
      p('Florian Broska', 'GER', 284),
      p('Jacopo Vasami', 'ITA', null, 'JR 2'),
      p('Thomas Faurel', 'FRA', 321),
      p('Miguel Damas', 'ESP', 289, 'IN'),
    ],
    mainNext: [
      p('Daniel Elahi Galan', 'COL', 290),
      p('Sean Cuenin', 'FRA', 299),
      p('Maxim Mrva', 'CZE', 304),
      p('Oriol Roca Batalla', 'ESP', 338),
      p('Max Hans Rehberg', 'GER', 339),
      p('Petr Brunclik', 'CZE', 340),
      p('Jonas Forejtek', 'CZE', 345),
      p('Marko Topo', 'GER', 348),
      p('Max Wiskandt', 'GER', 365),
    ],
    qualifying: [
      p('Daniel Elahi Galan', 'COL', 290),
      p('Sean Cuenin', 'FRA', 299),
      p('Oriol Roca Batalla', 'ESP', 338),
      p('Petr Brunclik', 'CZE', 340),
      p('Jonas Forejtek', 'CZE', 345),
      p('Marko Topo', 'GER', 348),
      p('Eduardo Ribeiro', 'BRA', 366),
      p('Marek Gengel', 'CZE', 373),
      p('Radu Mihai Papoe', 'ROU', 385),
      p('Javier Barranco Cosano', 'ESP', 397),
      p('Andrej Martin', 'SVK', 404),
      p('Nerman Fatic', 'BIH', 406),
      p('Beibit Zhukayev', 'KAZ', 413),
      p('Massimo Giunta', 'ITA', 418),
      p('Norbert Gombos', 'SVK', 423),
      p('Robert Strombachs', 'LAT', 440),
      p('Daniel Siniakov', 'CZE', 448),
      p('Matthew William Donald', 'CZE', 455),
      p('Milos Karol', 'SVK', 463),
      p('Lorenzo Carboni', 'ITA', 470),
    ],
    qualifyingNext: [
      p('Maxim Mrva', 'CZE', 304),
      p('Max Hans Rehberg', 'GER', 339),
      p('Max Wiskandt', 'GER', 365),
    ],
    recentMovement: ['Michele Ribecai withdrew', 'Miguel Damas moved into the main draw'],
  },
  {
    slug: 'roehampton',
    name: 'Roehampton',
    level: 'CH 50',
    surface: 'Hard',
    atpCode: '3123',
    main: [
      p('Elmer Moller', 'DEN', 190),
      p('Giles Hussey', 'GBR', 253),
      p('Max Basing', 'GBR', 257),
      p('Alastair Gray', 'GBR', 266),
      p('Matteo Martineau', 'FRA', 280),
      p('Matheus Pucinelli De Almeida', 'BRA', 297),
      p('Mert Alkaya', 'TUR', 298),
      p('Johannus Monday', 'GBR', 312),
      p('Michael Geerts', 'BEL', 337),
      p('Anton Matusevich', 'GBR', 342),
      p('Manas Dhamne', 'IND', 372),
      p('Jay Friend', 'JPN', 376),
      p('Yuta Shimizu', 'JPN', 380),
      p('Lui Maxted', 'GBR', 398),
      p('Maximus Jones', 'THA', 417),
      p('Adrian Boitan', 'ROU', 429),
      p('Lucas Poullain', 'FRA', 439),
      p('Devin Badenhorst', 'RSA', null, 'CO 10'),
      p('Ivan Ivanov', 'BUL', null, 'JR 7'),
      p('Iliyan Radulov', 'BUL', 441, 'IN'),
      p('Luca Potenza', 'ITA', 447, 'IN'),
    ],
    mainNext: [
      p('George Loffhagen', 'GBR', 453),
      p('Christian Langmo', 'USA', 457),
      p('Karim Bennani', 'MAR', 458),
      p('Alex Rybakov', 'USA', 475),
      p('Anton Shepp', 'NZL', 489),
      p('Viktor Durasovic', 'NOR', 490),
      p('Constantin Bittoun Kouzmine', 'FRA', 507),
      p('Koki Matsuda', 'JPN', 514),
    ],
    qualifying: [
      p('Oliver Tarvet', 'GBR', 433),
      p('George Loffhagen', 'GBR', 453),
      p('Christian Langmo', 'USA', 457),
      p('Alex Rybakov', 'USA', 475),
      p('Anton Shepp', 'NZL', 489),
      p('Viktor Durasovic', 'NOR', 490),
      p('Constantin Bittoun Kouzmine', 'FRA', 507),
      p('Fares Zakaria', 'EGY', 517),
      p('Emile Hudd', 'GBR', 518),
      p('Radu Albot', 'MDA', 519),
      p('Fausto Tabacco', 'ITA', 545),
      p('Peter Makk', 'HUN', 547),
      p('Filip Peliwo', 'POL', 548),
      p('James Story', 'GBR', 556),
      p('Alec Deckers', 'NED', 574),
      p('John Echeverria', 'ESP', 576),
      p('Leonardo Rossi', 'ITA', 599),
      p('Daniel De Jonge', 'NED', 603),
      p('Nicolas Tepmahc', 'FRA', 614),
    ],
    qualifyingNext: [
      p('Karim Bennani', 'MAR', 458),
      p('Koki Matsuda', 'JPN', 514),
    ],
    recentMovement: [
      'Hamish Stewart withdrew',
      'Cyril Vandermeersch withdrew',
      'Iliyan Radulov moved into the main draw',
      'Luca Potenza moved into the main draw',
    ],
  },
  {
    slug: 'sion',
    name: 'Sion',
    level: 'CH 50',
    surface: 'Clay',
    atpCode: '3133',
    main: [
      p('Lorenzo Giustino', 'ITA', 201),
      p('Juan Manuel La Serna', 'ARG', 282),
      p('Sandro Kopp', 'AUT', 286),
      p('Federico Bondioli', 'ITA', 291),
      p('Filippo Romano', 'ITA', 300),
      p('Duje Ajdukovic', 'CRO', 307),
      p('Calvin Hemery', 'FRA', 318),
      p('Marvin Moller', 'GER', 319),
      p('Enrico Dalla Valle', 'ITA', 323),
      p('Murkel Dellien', 'BOL', 327),
      p('Juan Estevez', 'ARG', 329),
      p('Facundo Mena', 'ARG', 330),
      p('Hernan Casanova', 'ARG', 334),
      p('Ognjen Milic', 'SRB', 336),
      p('Andrey Chepelev', 'RUS', 351),
      p('Tommaso Compagnucci', 'ITA', 358),
      p('Petr Nesterov', 'BUL', 360),
      p('Lucio Ratti', 'ARG', 364),
      p('Dimitar Kuzmanov', 'BUL', 375),
      p('Mathys Erhard', 'FRA', 383),
      p('Max Dahlin', 'SWE', null, 'CO 9'),
    ],
    mainNext: [
      p('Georgii Kravchenko', 'UKR', 387),
      p('Raphael Perot', 'FRA', 388),
      p('Geoffrey Blancaneaux', 'FRA', 408),
      p('Johan Nikles', 'SUI', 412),
      p('Oleg Prihodko', 'MKD', 414),
      p('Massimo Giunta', 'ITA', 418),
      p('Mika Brunold', 'SUI', 420),
      p('Henry Bernet', 'SUI', 426),
      p('Valerio Aboian', 'ARG', 427),
      p('Vladyslav Orlov', 'UKR', 430),
    ],
    qualifying: [
      p('Dominic Stricker', 'SUI', 324),
      p('Raphael Perot', 'FRA', 388),
      p('Johan Nikles', 'SUI', 412),
      p('Mika Brunold', 'SUI', 420),
      p('Henry Bernet', 'SUI', 426),
      p('Dylan Dietrich', 'SUI', 434),
      p('Patrick Schoen', 'SUI', 488),
      p('Ryan Nijboer', 'NED', 499),
      p('Benjamin Hassan', 'LBN', 506),
      p('Alex Marti Pujolras', 'ESP', 516),
      p('Luca Staeheli', 'SUI', 526),
      p('Luca Wiedenmann', 'GER', 541),
      p('Dimitris Sakellaridis', 'GRE', 567),
      p('Gerard Campana Lee', 'KOR', 582),
      p('Nino Ehrenschneider', 'GER', 593),
      p('Oleksandr Ovcharenko', 'UKR', 596),
      p('Lorenzo Bocchi', 'ITA', 597),
      p('Kai Wehnelt', 'GER', 618),
      p('Maximo Zeitune', 'ARG', 628),
      p('Theo Papamalamis', 'FRA', null),
    ],
    qualifyingNext: [
      p('Georgii Kravchenko', 'UKR', 387),
      p('Geoffrey Blancaneaux', 'FRA', 408),
      p('Oleg Prihodko', 'MKD', 414),
      p('Massimo Giunta', 'ITA', 418),
      p('Valerio Aboian', 'ARG', 427),
      p('Vladyslav Orlov', 'UKR', 430),
    ],
    recentMovement: [],
  },
];

export function getAug17EntryList(slug: string | undefined): Aug17EntryList {
  return AUG17_ENTRY_LISTS.find((event) => event.slug === slug) ?? AUG17_ENTRY_LISTS[0];
}
